version: "3.9"

services:
    mysql:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/x86_64
        container_name: gradwork-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
